### ISSUE TITLE
Where does the list of required shared libraries come from?

### ISSUE THREAD

**Issue by ole** [tonisuter/aws-lambda-swift#5]
Hi Toni, great project! I found it through your post on the Swift forums.

I modified your project to write my own little function. Since my function uses Swift 5 features, I switched the Docker image to [codevapor/swift:5.0](https://hub.docker.com/r/codevapor/swift).

Everything seemed to work, but when I tested my function on AWS, it failed with:

```
error while loading shared libraries: libswiftDispatch.so: cannot open shared object file: No such file or directory
```

<img width="1096" alt="screen shot 2018-12-25 at 21 04 36" src="https://user-images.githubusercontent.com/5010/50426249-75b74e80-0889-11e9-9ba6-d31646a7d06e.png">

It looks like the source of this error is that the names of one or more shared libraries changed in Swift 5, e.g. `libdispatch.so` is now called `libswiftDispatch.so`. So I need to update the list of shared libraries in the Makefile. Can I ask how you generated this list?

Running `ldd [path_to_my_binary]` on Linux seems to be an option to get a list of the shared libraries loaded by an executable, but I wanted to ask if you used a different option.

Thanks and happy holidays!

PS: Don't let me stop you from enjoying your holidays. This isn't urgent.

**Comment by tonisuter** [comment]
Hi Ole

Thank you :-)! That's a good question.

I tried several things. First, I tried to statically link the standard library using swiftc's `-static-stdlib` flag. This works fine when the program only uses the standard library. However, it doesn't work on Linux when the program imports Foundation due to a bug (see [SR-2205](https://bugs.swift.org/browse/SR-2205)).

So I created a very simple Swift executable in a `swift:latest` Docker container that just imports Foundation and prints the current date. I used the `ldd` command to get a list of the shared libraries that the executable uses (see [Stackoverflow](https://stackoverflow.com/questions/50159/how-to-show-all-shared-libraries-used-by-executables-in-linux)):

```bash
$ docker run --rm -it swift /bin/bash
root@0f4fa22b3c5f:/# mkdir TestPkg
root@0f4fa22b3c5f:/# cd TestPkg
root@0f4fa22b3c5f:/TestPkg# swift package init --type executable
root@0f4fa22b3c5f:/TestPkg# echo "import Foundation" > Sources/TestPkg/main.swift
root@0f4fa22b3c5f:/TestPkg# echo "print(Date())" >> Sources/TestPkg/main.swift
root@0f4fa22b3c5f:/TestPkg# swift build
root@0f4fa22b3c5f:/TestPkg# ldd .build/debug/TestPkg | sed -e 's/\t//' | sed -e 's/.*=..//' | sed -e 's/ (0.*)//' | sort
```

On AWS, I then tried to execute the lambda while setting the library search path to a directory that contains all of those shared libraries like this:

```bash
LD_LIBRARY_PATH=./shared-libs ./lambda
```

That didn't work due to a relocation error. Thanks to [this repository](https://github.com/choefele/swift-lambda-app/blob/master/Shim/index.js) I figured out that I can execute the lambda through the dynamic linker (i.e., the [`ld-linux-x86-64.so.2`](https://unix.stackexchange.com/questions/400621/what-is-lib64-ld-linux-x86-64-so-2-and-why-can-it-be-used-to-execute-file) file) which somehow solves the relocation error. This is what I'm now doing in the `bootstrap` file and it seems to work quite well.

I hope this helps. Happy holidays to you, too!

**Comment by ole** [comment]
Thanks @tonisuter, that's very helpful. I'll try again and report back.

**Comment by ole** [comment]
Copying the list produced by `ldd` into the Makefile worked, so I can confirm (unsurprisingly) the process also works with the current Swift 5 prerelease using the 
[codevapor/swift:5.0](https://hub.docker.com/r/codevapor/swift) Docker image. Thanks again for the help.
