### ISSUE TITLE
Failure of 'make package_layer' command.

### ISSUE THREAD

**Issue by WayneEld** [tonisuter/aws-lambda-swift#8]
A great project. I love Swift and AWS and I am looking to combine the two with your amazing work and hoping to contribute in the future if I can.

I do have an issue when creating the swift-runtime zip file. I do feel that I am getting a user side error when running the `make package_layer` command. I receive the following errors:
`cp: cannot stat '/lib/x86_64-linux-gnu/libcrypto.so.1.0.0': No such file or directory
cp: cannot stat '/lib/x86_64-linux-gnu/libssl.so.1.0.0': No such file or directory
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libicudata.so.55': No such file or directory
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libicui18n.so.55': No such file or directory
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libicuuc.so.55': No such file or directory
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libidn.so.11': No such file or directory
make: *** [package_layer] Error 1`

I do feel like I am missing those libraries locally but can't seem to figure out the installion of them. Any help will be appreciate. (I do feel like this is a beginner issue so apologies in advance.)

**Comment by tonisuter** [comment]
Hi. Thanks for reporting this issue. This happens because the official Swift docker image (see https://hub.docker.com/_/swift/) has been recently updated to support Swift 5 and I haven't updated this project yet. I plan to do that within the next week or so. In the meantime, you could just change line 42 and line 48 in the Makefile from `swift` to `swift:4.2.4`. This way, Docker will download the image for Swift 4.2.4 and the Makefile should work.

**Comment by WayneEld** [comment]
Great thanks. Works perfectly to great the `swift-lambda-runtime.zip` file.
